basePath: /v1
definitions:
  entity.Raffle:
    properties:
      id:
        example: 61f0c143ad06223fa03910b0
        type: string
      name:
        example: Rifa
        type: string
      status:
        example: Available
        type: string
      totalNumbers:
        example: 10
        type: integer
      totalSold:
        example: 1
        type: integer
      value:
        example: 5
        type: integer
    type: object
  entity.Translation:
    properties:
      destination:
        example: en
        type: string
      original:
        example: текст для перевода
        type: string
      source:
        example: auto
        type: string
      translation:
        example: text for translation
        type: string
    type: object
  v1.availableResponse:
    properties:
      available:
        items:
          $ref: '#/definitions/entity.Raffle'
        type: array
    type: object
  v1.doRaffleRequest:
    properties:
      name:
        example: rifa faca
        type: string
      totalNumbers:
        example: 20
        type: integer
      value:
        example: 1
        type: integer
    required:
    - name
    - totalNumbers
    - value
    type: object
  v1.doTranslateRequest:
    properties:
      destination:
        example: en
        type: string
      original:
        example: текст для перевода
        type: string
      source:
        example: auto
        type: string
    required:
    - destination
    - original
    - source
    type: object
  v1.historyResponse:
    properties:
      history:
        items:
          $ref: '#/definitions/entity.Translation'
        type: array
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a translation service as an example
  title: Go Clean Template API
  version: "1.0"
paths:
  /available/do-create:
    post:
      consumes:
      - application/json
      description: Create a Raffle
      operationId: do-create
      parameters:
      - description: Set up raffle
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.doRaffleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Raffle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Create
      tags:
      - raffle
  /raffle/available:
    get:
      consumes:
      - application/json
      description: Show all available raffles
      operationId: raffle
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.availableResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Show raffles
      tags:
      - translation
  /translation/do-translate:
    post:
      consumes:
      - application/json
      description: Translate a text
      operationId: do-translate
      parameters:
      - description: Set up translation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.doTranslateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Translation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Translate
      tags:
      - translation
  /translation/history:
    get:
      consumes:
      - application/json
      description: Show all translation history
      operationId: history
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.historyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Show history
      tags:
      - translation
swagger: "2.0"
