name: CD

env:
  AZURE_WEBAPP_NAME: appservice-dev-rifa  # set this to the name of your Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: acrdevrifa.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t acrdevrifa.azurecr.io/rifa:${{ github.sha }}
        docker push acrdevrifa.azurecr.io/rifa:${{ github.sha }}  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'acrdevrifa.azurecr.io/rifa:${{ github.sha }}'
